### ISSUE TITLE
Class "Serenity\\Responders\FailedPasswordConfirmation" does not exist when execute "php lotus serve" on Windows

### ISSUE THREAD

**Issue by Sulaymon-dev** [jetstreamlabs/serenity#3]
After installing the dependencies, when the "php lotus serve" executed, I get following error:

![image](https://user-images.githubusercontent.com/40419449/224898892-a79c98ac-0042-457f-9aee-9739d17971d2.png)

### PHP version: 
XAMPP, PHP 8.1.6 (cli) (built: May 11 2022 08:55:59) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies

**Comment by secondmanveran** [comment]
This was fixed.
